import * as THREE from 'three';
import { PrimaryGameLogicController } from './Game.js';

/**
 * APPLICATION ENTRY POINT
 * This file handles the initial setup of the Three.js rendering engine,
 * the scene graph, and the main animation loop that drives the game.
 */

/**
 * INITIAL SCENE GRAPH SETUP:
 * Every Three.js application needs a Scene to hold all 3D objects.
 */
const primaryRenderingScene = new THREE.Scene();

// We set a very dark blue background color to simulate the depths of outer space.
primaryRenderingScene.background = new THREE.Color(0x050510);

/**
 * CAMERA CONFIGURATION:
 * We use a PerspectiveCamera to provide a realistic sense of depth.
 * Arguments: (Field of View, Aspect Ratio, Near Clipping Plane, Far Clipping Plane)
 */
const primaryPerspectiveCamera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);

// We position the camera high above the X-Y plane looking down (backwards along Z).
primaryPerspectiveCamera.position.z = 60;

/**
 * RENDERER INITIALIZATION:
 * The WebGLRenderer translates the 3D scene data onto an HTML Canvas.
 */
const primaryWebGLGraphicsRenderer = new THREE.WebGLRenderer({ antialias: true });
primaryWebGLGraphicsRenderer.setSize(window.innerWidth, window.innerHeight);

// Attach the canvas element generated by Three.js into our HTML structure.
document.getElementById('app').appendChild(primaryWebGLGraphicsRenderer.domElement);

/**
 * GLOBAL LIGHTING:
 * 1. Ambient Light provides a baseline level of visibility for all objects.
 * 2. Directional Light simulates a distant sun, creating shadows and highlights.
 */
const generalAmbientIllumination = new THREE.AmbientLight(0x404040, 2);
primaryRenderingScene.add(generalAmbientIllumination);

const directionalSolarLightSource = new THREE.DirectionalLight(0xffffff, 1.5);
directionalSolarLightSource.position.set(10, 20, 30);
primaryRenderingScene.add(directionalSolarLightSource);

/**
 * RESPONSIVE VIEWPORT HANDLING:
 * We must update the camera and renderer dimensions whenever the user resizes their browser.
 */
window.addEventListener('resize', () => {
    primaryPerspectiveCamera.aspect = window.innerWidth / window.innerHeight;
    primaryPerspectiveCamera.updateProjectionMatrix();
    primaryWebGLGraphicsRenderer.setSize(window.innerWidth, window.innerHeight);
});

/**
 * GAME ENGINE INITIALIZATION:
 * Instantiate the central controller that handles asteroids, player movement, and collision.
 */
const activeGameLogicEngine = new PrimaryGameLogicController(primaryRenderingScene, primaryPerspectiveCamera);

/**
 * ENGINE CLOCK:
 * We use a THREE.Clock to accurately measure the time elapsed between frames (delta time).
 */
const highPrecisionGameTimingClock = new THREE.Clock();

/**
 * MAIN ANIMATION LOOP:
 * This function iterates at approximately 60 frames per second.
 */
function primaryExecutionAnimationLoop() {
  // Use the native browser API to schedule the next frame iteration.
  requestAnimationFrame(primaryExecutionAnimationLoop);
  
  /**
   * DELTA TIME CALCULATION:
   * We need to know exactly how much time passed since the last loop 
   * to ensure movement speed is consistent regardless of frame-rate.
   */
  const timeElapsedInSecondsSinceLastFrame = highPrecisionGameTimingClock.getDelta();
  
  // Advance the game logic by the calculated time delta.
  activeGameLogicEngine.processGameLogicFrameUpdate(timeElapsedInSecondsSinceLastFrame);
  
  // Instruct the renderer to draw the current state of the scene from the camera's perspective.
  primaryWebGLGraphicsRenderer.render(primaryRenderingScene, primaryPerspectiveCamera);
}

// Kickstart the animation loop.
primaryExecutionAnimationLoop();
